apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quest-diagnostics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ak3hay/quest-diagnostics-manifests.git
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: quest-diagnostics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
